# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: fffc25f3af74180a7ae799bac3e5507cfac1653111d0949bb9fad43a9a2eda8b6339c1568d489c5aca81acec82effd065021466e879592a70accff9cde4e2041

test:
  secret_key_base: 2d8d20e225e832400d75999ebc7a4f84e0a2ab246ecfbcf2bee4fb0bae63da84c9a1e4ffcd868c149bfa0b5db77f64dce0d2e086d74c89a198979fec2646de6c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
